# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint generator/__init__.py generator/generator.py test/__init__.py test/test_generator.py
    - name: Build wily
      run: |
        wily build
        wily diff generator/ -r master
    - name: Show wily report
      run: |
        wily report generator/generator.py
        wily report test/test_generator.py
    - name: Show wily rank
      run: |
        wily rank generator/ 
        wily rank test/ 
        wily rank .
    - name: Test with pytest
      run: |
        pytest
